version: "3.7"
services:

  decisions_express:
    build: 
      context: ./decisions-express
    container_name: decision_express
    command: npm run dev
    volumes:
      - ./decisions-express:/app/
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      MONGO_DATABASE_URL: mongodb://mongodb:27017/decision_app
    depends_on:
      - mongodb

  decisions_gatsby:
    build: 
      context: ./decisions-gatsby
    container_name: decision_gatsby
    command: npm run develop
    volumes:
      - ./decisions-gatsby:/app/
      - /app/node_modules
    ports:
      - 8000:8000
  
  mongodb:
    image: mongo:4.1
    container_name: mongodb
    volumes:
      - data-volume:/data/db
    ports:
      - 27017:27017

volumes:
  data-volume: